### ISSUE TITLE
performance_rnn: cannot use bundle from new trained model 

### ISSUE THREAD

**Issue by eps696** [magenta/magenta#1364]
hello, 
after training new model for performance_rnn on maestro dataset, got the following issue: 
- training went reasonably well (stopped at 80k with accuracy~0.5, just to test), 
- midi tracks generation from the checkpoint files also worked well, 
- saved the bundle from the checkpoint files without errors, 
- midi tracks generation from the bundle failed with errors. 

the only additional hparam specified was `use_cudnn`. python 3.5.2, windows 10, cuda 9. 
tried that on magenta 0.3.14 with tf 1.8.0, magenta 0.3.19 from pip with tf 1.12.0, magenta from github (again with tf 1.12.0) - the error log varied a bit in the beginning, but the most errors and results stayed intact. the same process worked flawlessly with polyphony_rnn. 
// upd: the same issue was with the Lakh midi dataset

= training (went OK)
```
performance_rnn_train --config=performance_with_dynamics_compact --run_dir=maestro --sequence_example_file=C:\X\midi\maestro-perf\training_performances.tfrecord --hparams="use_cudnn=True" --summary_frequency 100 --save_frequency 300

c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\IPython\lib\pretty.py:91: DeprecationWarning: IPython.utils.signatures backport for Python 2 is deprecated in IPython 6, which only supports Python 3
  from IPython.utils.signatures import signature
INFO:tensorflow:hparams = {'learning_rate': 0.001, 'dropout_keep_prob': 1.0, 'attn_length': 0, 'clip_norm': 3, 'use_cudnn': True, 'batch_size': 64, 'rnn_layer_sizes': [512, 512, 512], 'residual_connections': False}
INFO:tensorflow:Train dir: maestro\train
[ ... multiple TF deprecation warnings omitted ... ]
INFO:tensorflow:Counting records in C:\X\midi\maestro-perf\training_performances.tfrecord.
INFO:tensorflow:Number of records is at least 100.
INFO:tensorflow:[<tf.Tensor 'random_shuffle_queue_Dequeue:0' shape=(?, 1) dtype=float32>, <tf.Tensor 'random_shuffle_queue_Dequeue:1' shape=(?,) dtype=int64>, <tf.Tensor 'random_shuffle_queue_Dequeue:2' shape=() dtype=int32>]
INFO:tensorflow:Starting training loop...
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2018-11-27 10:39:27.912110: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-11-27 10:39:28.089894: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 9.10GiB
2018-11-27 10:39:28.094360: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-11-27 10:39:33.675526: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-27 10:39:33.678729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2018-11-27 10:39:33.680523: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2018-11-27 10:39:33.682288: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8788 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into maestro\train\model.ckpt.
INFO:tensorflow:Accuracy 0.002, Perplexity 388.13, Loss 5.961, Step 0
INFO:tensorflow:global_step/sec: 6.99861
INFO:tensorflow:Accuracy 0.026, Perplexity 165.34, Loss 5.108, Step 100
INFO:tensorflow:global_step/sec: 7.53551
... etc.
```

= tracks generation from the checkpoint (went OK)
```
performance_rnn_generate --config=performance_with_dynamics --hparams="use_cudnn=True" --run_dir=maestro --output_dir=_out --num_outputs=2 --num_steps=1000 --primer_melody="[60,62,64,65,67,69,71,72]"

c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\IPython\lib\pretty.py:91: DeprecationWarning: IPython.utils.signatures backport for Python 2 is deprecated in IPython 6, which only supports Python 3
  from IPython.utils.signatures import signature
INFO:tensorflow:hparams = {'use_cudnn': True, 'residual_connections': False, 'attn_length': 0, 'dropout_keep_prob': 1.0, 'batch_size': 1, 'learning_rate': 0.001, 'clip_norm': 3, 'rnn_layer_sizes': [512, 512, 512]}
2018-11-27 16:12:08.490663: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-11-27 16:12:08.667704: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 9.10GiB
2018-11-27 16:12:08.672899: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-11-27 16:12:20.448191: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-27 16:12:20.450833: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2018-11-27 16:12:20.452191: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2018-11-27 16:12:20.453774: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8788 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Checkpoint used: maestro\train\model.ckpt-80600
INFO:tensorflow:Restoring parameters from maestro\train\model.ckpt-80600
INFO:tensorflow:Need to generate 899 more steps for this sequence, will try asking for 540 RNN steps
INFO:tensorflow:Beam search yields sequence with log-likelihood: -1254.742432
INFO:tensorflow:Need to generate 899 more steps for this sequence, will try asking for 540 RNN steps
INFO:tensorflow:Beam search yields sequence with log-likelihood: -1083.906128
INFO:tensorflow:Wrote 2 MIDI files to _out
```

= making bundle from the checkpoint (went OK)
```
performance_rnn_generate --config=performance_with_dynamics_compact --hparams="use_cudnn=True" --run_dir=maestro --bundle_file=maestro_dynamics.mag --bundle_description "Perf Dyn Maestro" --save_generator_bundle

c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\IPython\lib\pretty.py:91: DeprecationWarning: IPython.utils.signatures backport for Python 2 is deprecated in IPython 6, which only supports Python 3
  from IPython.utils.signatures import signature
INFO:tensorflow:Saving generator bundle to maestro_dynamics.mag
INFO:tensorflow:hparams = {'residual_connections': False, 'use_cudnn': True, 'rnn_layer_sizes': [512, 512, 512], 'dropout_keep_prob': 1.0, 'learning_rate': 0.001, 'clip_norm': 3, 'batch_size': 1, 'attn_length': 0}
2018-11-27 16:14:13.638613: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-11-27 16:14:13.818892: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 9.10GiB
2018-11-27 16:14:13.823441: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-11-27 16:14:17.687832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-27 16:14:17.690745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2018-11-27 16:14:17.692462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2018-11-27 16:14:17.694448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8788 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Checkpoint used: maestro\train\model.ckpt-80600
INFO:tensorflow:Restoring parameters from maestro\train\model.ckpt-80600
WARNING:tensorflow:*******************************************************
WARNING:tensorflow:TensorFlow's V1 checkpoint format has been deprecated.
WARNING:tensorflow:Consider switching to the more efficient V2 format:
WARNING:tensorflow:   `tf.train.Saver(write_version=tf.train.SaverDef.V2)`
WARNING:tensorflow:now on by default.
WARNING:tensorflow:*******************************************************
```

= tracks generation from the bundle (FAILED)
```
performance_rnn_generate --config=performance_with_dynamics --bundle_file=maestro_dynamics.mag --output_dir=_out --num_outputs=2 --num_steps=1000 --primer_melody="[60,62,64,65,67,69,71,72]"

c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\IPython\lib\pretty.py:91: DeprecationWarning: IPython.utils.signatures backport for Python 2 is deprecated in IPython 6, which only supports Python 3
  from IPython.utils.signatures import signature
2018-11-27 16:17:00.391574: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-11-27 16:17:00.571016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 9.10GiB
2018-11-27 16:17:00.575342: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-11-27 16:17:05.102230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-27 16:17:05.104800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2018-11-27 16:17:05.106119: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2018-11-27 16:17:05.107563: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8788 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from C:\Users\eps\AppData\Local\Temp\tmpy4hc4kx3\model.ckpt
INFO:tensorflow:Need to generate 899 more steps for this sequence, will try asking for 540 RNN steps
Traceback (most recent call last):
  File "c:\users\eps\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\eps\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\eps\AppData\Local\Programs\Python\Python35\Scripts\performance_rnn_generate.exe\__main__.py", line 9, in <module>
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\magenta\models\performance_rnn\performance_rnn_generate.py", line 290, in console_entry_point
    tf.app.run(main)
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\magenta\models\performance_rnn\performance_rnn_generate.py", line 286, in main
    run_with_flags(generator)
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\magenta\models\performance_rnn\performance_rnn_generate.py", line 245, in run_with_flags
    generated_sequence = generator.generate(primer_sequence, generator_options)
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\magenta\music\sequence_generator.py", line 194, in generate
    return self._generate(input_sequence, generator_options)
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\magenta\models\performance_rnn\performance_sequence_generator.py", line 231, in _generate
    len(performance) + rnn_steps_to_gen, performance, **args)
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\magenta\models\performance_rnn\performance_model.py", line 82, in generate_performance
    extend_control_events_callback=extend_control_events_callback)
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\magenta\models\shared\events_rnn_model.py", line 378, in _generate_events
    steps_per_iteration=steps_per_iteration)
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\magenta\common\beam_search.py", line 134, in beam_search
    beam_entries, generate_step_fn, branch_factor, first_iteration_num_steps)
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\magenta\common\beam_search.py", line 67, in _generate_branches
    all_sequences, all_states, all_scores)
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\magenta\models\shared\events_rnn_model.py", line 232, in _generate_step
    temperature)
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\magenta\models\shared\events_rnn_model.py", line 127, in _generate_step_for_batch
    [graph_final_state, graph_softmax], feed_dict)
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "c:\users\eps\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 26, 388) for Tensor 'Placeholder:0', which has shape '(1, ?, 1)'
```

**Comment by adarob** [comment]
If you extract the checkpoint from the bundle, can you then make it work with that checkpoint?

**Comment by eps696** [comment]
yes, 'unbundled' checkpoint works again. 
here is that problematic bundle: https://yadi.sk/d/yYOojBLh-H0wYQ

**Comment by eps696** [comment]
[occasionally passed by this old issue]
it seems there was some confusion with config. i supposed it was trained as `performance_with_dynamics_compact` (and resulted checkpoint worked with that config), but the bundle worked only as `performance_with_dynamics`. need to keep an eye on that for future experiments..
