### ISSUE TITLE
AttributeError: 'module' object has no attribute 'py_function'

### ISSUE THREAD

**Issue by aletote** [magenta/magenta#1539]
(base) ales-MacBook-Pro:Desktop ale$ music_vae_train --config=cat-mel_2bar_big --run_dir=\midis --mode=train --examples_path=\notesequences.tfrecord
/anaconda/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
/anaconda/lib/python2.7/site-packages/bokeh/core/json_encoder.py:52: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  NP_EPOCH = np.datetime64('1970-01-01T00:00:00Z')
2019-05-28 15:16:09.727736: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Building MusicVAE model with BidirectionalLstmEncoder, CategoricalLstmDecoder, and hparams:
{'grad_clip': 1.0, 'z_size': 512, 'free_bits': 0, 'max_seq_len': 32, 'residual_encoder': False, 'grad_norm_clip_to_zero': 10000, 'learning_rate': 0.001, 'conditional': True, 'use_cudnn': False, 'min_learning_rate': 1e-05, 'sampling_schedule': 'inverse_sigmoid', 'dec_rnn_size': [2048, 2048, 2048], 'residual_decoder': False, 'decay_rate': 0.9999, 'beta_rate': 0.99999, 'sampling_rate': 1000, 'enc_rnn_size': [2048], 'batch_size': 512, 'max_beta': 0.5, 'dropout_keep_prob': 1.0, 'clip_mode': 'global_norm'}
I0528 15:16:09.737344 4444100032 tf_logging.py:115] Building MusicVAE model with BidirectionalLstmEncoder, CategoricalLstmDecoder, and hparams:
{'grad_clip': 1.0, 'z_size': 512, 'free_bits': 0, 'max_seq_len': 32, 'residual_encoder': False, 'grad_norm_clip_to_zero': 10000, 'learning_rate': 0.001, 'conditional': True, 'use_cudnn': False, 'min_learning_rate': 1e-05, 'sampling_schedule': 'inverse_sigmoid', 'dec_rnn_size': [2048, 2048, 2048], 'residual_decoder': False, 'decay_rate': 0.9999, 'beta_rate': 0.99999, 'sampling_rate': 1000, 'enc_rnn_size': [2048], 'batch_size': 512, 'max_beta': 0.5, 'dropout_keep_prob': 1.0, 'clip_mode': 'global_norm'}
INFO:tensorflow:
Encoder Cells (bidirectional):
  units: [2048]

I0528 15:16:09.740672 4444100032 tf_logging.py:115] 
Encoder Cells (bidirectional):
  units: [2048]

INFO:tensorflow:
Decoder Cells:
  units: [2048, 2048, 2048]

I0528 15:16:09.744151 4444100032 tf_logging.py:115] 
Decoder Cells:
  units: [2048, 2048, 2048]

INFO:tensorflow:Reading examples from file: notesequences.tfrecord
I0528 15:16:09.753292 4444100032 tf_logging.py:115] Reading examples from file: notesequences.tfrecord
WARNING:tensorflow:From /anaconda/lib/python2.7/site-packages/magenta/models/music_vae/data.py:1224: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
W0528 15:16:09.873902 4444100032 tf_logging.py:125] From /anaconda/lib/python2.7/site-packages/magenta/models/music_vae/data.py:1224: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
Traceback (most recent call last):
  File "/anaconda/bin/music_vae_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/anaconda/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 340, in console_entry_point
    tf.app.run(main)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/anaconda/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 336, in main
    run(configs.CONFIG_MAP)
  File "/anaconda/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 317, in run
    task=FLAGS.task)
  File "/anaconda/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 169, in train
    optimizer = model.train(**_get_input_tensors(dataset_fn(), config))
  File "/anaconda/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 304, in dataset_fn
    cache_dataset=FLAGS.cache_dataset)
  File "/anaconda/lib/python2.7/site-packages/magenta/models/music_vae/data.py", line 1253, in get_dataset
    dataset = dataset.map(note_sequence_augmenter.tf_augment)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1038, in map
    return MapDataset(self, map_func)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2611, in __init__
    map_func, "Dataset.map()", input_dataset)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1860, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 864, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1794, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "/anaconda/lib/python2.7/site-packages/magenta/models/music_vae/data.py", line 154, in tf_augment
    augmented_note_sequence_scalar = tf.py_function(
AttributeError: 'module' object has no attribute 'py_function'

**Comment by aletote** [comment]
Nevermind, 'pip3 install magenta' instead of 'pip install magenta' solved it.
