### ISSUE TITLE
Problem with training MusicVAE is Magenta 2.0.1

### ISSUE THREAD

**Issue by AI-Guru** [magenta/magenta#1742]
Hi everybody,

I am very excited about the newest magenta release!

I tried to train MusicVAE. Unfortunately I got this error:
```
interleave() got an unexpected keyword argument 'deterministic'
```

Here is the traceback:
```
Traceback (most recent call last):
  File "music_vae_train.py", line 342, in <module>
    console_entry_point()
  File "music_vae_train.py", line 338, in console_entry_point
    tf.app.run(main)
  File "/Users/xxx/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/xxx/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/xxx/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "music_vae_train.py", line 333, in main
    run(configs.CONFIG_MAP)
  File "music_vae_train.py", line 314, in run
    task=FLAGS.task)
  File "music_vae_train.py", line 164, in train
    optimizer = model.train(**_get_input_tensors(dataset_fn(), config))
  File "music_vae_train.py", line 301, in dataset_fn
    cache_dataset=FLAGS.cache_dataset)
  File "/Users/xxx/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/magenta/models/music_vae/data.py", line 1796, in get_dataset
    dataset = files.interleave(tf_file_reader, deterministic=not is_training)
TypeError: interleave() got an unexpected keyword argument 'deterministic'
```

I guess that is just a minor incompatibility issue.

Keep up the great work!

Best,
Tristan

**Comment by AI-Guru** [comment]
Addendum: I upgraded Tensorflow from 2.1.0 to 2.2.0. Now this error message is gone. Maybe make 2.2.0 a requirement?

**Comment by adarob** [comment]
I don't want to add a strict dependency since other parts of the codebase do not play well with 2.x (e.g., Music Transformer). We may want to add `extras_require` for different models. Also, if this is the only thing blocking us from using earlier version of tf, we can just not set determinism.  @fjord, thoughts?
