### ISSUE TITLE
No gradient defined - Failed to train MusicVAE with Magenta 2.0.1

### ISSUE THREAD

**Issue by AI-Guru** [magenta/magenta#1743]
Hi,

I am so happy that the developers react swiftly to the issues :D

I ran into another issue. Should be a rather small one. I tried to train MusicVAE like this:
```
music_vae_train \
--config=cat-mel_2bar_small \
--run_dir=. \
--mode=train \
--examples_path=notesequences.tfrecord
```

I get a lot of output and then the script terminates. Traceback:
```
Traceback (most recent call last):
  File "/Users/tristanbehrens/Development/python-venvs/tf2-p37/bin/music_vae_train", line 8, in <module>
    sys.exit(console_entry_point())
  File "/Users/tristanbehrens/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 336, in console_entry_point
    tf.app.run(main)
  File "/Users/tristanbehrens/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/tristanbehrens/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/tristanbehrens/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/tristanbehrens/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 331, in main
    run(configs.CONFIG_MAP)
  File "/Users/tristanbehrens/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 312, in run
    task=FLAGS.task)
  File "/Users/tristanbehrens/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 172, in train
    grads, var_list = list(zip(*optimizer.compute_gradients(model.loss)))
  File "/Users/tristanbehrens/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/tensorflow/python/training/optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/Users/tristanbehrens/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 172, in gradients
    unconnected_gradients)
  File "/Users/tristanbehrens/Development/python-venvs/tf2-p37/lib/python3.7/site-packages/tensorflow/python/ops/gradients_util.py", line 623, in _GradientsHelper
    (op.name, op.type))
LookupError: No gradient defined for operation 'decoder/while/BasicDecoderStep/decoder/multi_rnn_cell/cell_1/lstm_cell/LSTMBlockCell' (op type: LSTMBlockCell)
```

Any ideas?

**Comment by AI-Guru** [comment]
Works with magenta 1.X.

**Comment by adarob** [comment]
Already tracking in #1739
