### ISSUE TITLE
arbitrary_image_stylization: 'scipy.misc' has no attribute 'imread'

### ISSUE THREAD

**Issue by anlexmatos** [magenta/magenta#1752]
Attempting to run the first example command from [here](https://github.com/magenta/magenta/tree/master/magenta/models/arbitrary_image_stylization) yields the following output:
```
Traceback (most recent call last):
  File "~/anaconda3/envs/magenta/bin/arbitrary_image_stylization_with_weights", line 8, in <module>
    sys.exit(console_entry_point())
  File "~/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/arbitrary_image_stylization/arbitrary_image_stylization_with_weights.py", line 178, in console_entry_point
    tf.app.run(main)
  File "~/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "~/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "~/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "~/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/arbitrary_image_stylization/arbitrary_image_stylization_with_weights.py", line 112, in main
    content_img_np = image_utils.load_np_image_uint8(content_img_path)[:, :, :
  File "~/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/image_stylization/image_utils.py", line 399, in load_np_image_uint8
    image = scipy.misc.imread(f.name)
AttributeError: module 'scipy.misc' has no attribute 'imread'
```

**Comment by adarob** [comment]
Can you try pip installing Pillow (https://pypi.org/project/Pillow/)? It should be a dep already but please reopen if that doesn't fix your problem.

**Comment by anlexmatos** [comment]
Pillow is already installed, and the original AttributeError remains.

```
Requirement already satisfied: Pillow in ~/anaconda3/envs/magenta/lib/python3.7/site-packages (7.1.2)
```

**Comment by anlexmatos** [comment]
By the way, I'm [unable](https://stackoverflow.com/a/21333938) to reopen an issue that was closed by a repo collaborator.

**Comment by traysiMay** [comment]
Having the same issue here.

**Comment by adarob** [comment]
What happens if you do `pip install scipy==1.2.0` after installing magenta?

**Comment by traysiMay** [comment]
I actually just downgraded to scipy==1.1.0 in my magenta env, got a few TensorFlow compatibility warnings, but ultimately I was able to run an image stylization model :)

**Comment by anlexmatos** [comment]
> 
> 
> What happens if you do
> 
> ```
> pip uninstall scipy
> pip install scipy==1.2.2
> ```
> 
> after installing magenta?

This worked for me.
