### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [No files matched pattern: ]

### ISSUE THREAD

**Issue by James-qq** [magenta/magenta#1814]
When I use my own tfrecord file to train, the command is as follows:
```
TRAIN_EXAMPLEiS='./maps_config2_test.tfrecord'
RUN_DIR='./result'

onsets_frames_transcription_train \
  --examples_path="${TRAIN_EXAMPLES}" \
  --model_dir="${RUN_DIR}" \
  --mode='train'
```
The error message is as follows：
```
I0906 23:51:03.352571 140561650476864 session_manager.py:508] Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
I0906 23:51:06.019742 140561650476864 basic_session_run_hooks.py:614] Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into ./result/model.ckpt.
I0906 23:51:06.024248 140561650476864 basic_session_run_hooks.py:618] Saving checkpoints for 0 into ./result/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
I0906 23:51:08.109029 140561650476864 basic_session_run_hooks.py:626] Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:training_loop marked as finished
I0906 23:51:08.592379 140561650476864 error_handling.py:115] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0906 23:51:08.592609 140561650476864 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [No files matched pattern: ]
	 [[{{node list_files/assert_not_empty/Assert}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qianqi/anaconda3/envs/magenta/bin/onsets_frames_transcription_train", line 33, in <module>
    sys.exit(load_entry_point('magenta', 'console_scripts', 'onsets_frames_transcription_train')())
  File "/home/qianqi/Desktop/magenta/magenta/models/onsets_frames_transcription/onsets_frames_transcription_train.py", line 123, in console_entry_point
    tf.app.run(main)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/qianqi/Desktop/magenta/magenta/models/onsets_frames_transcription/onsets_frames_transcription_train.py", line 118, in main
    additional_trial_info=additional_trial_info)
  File "/home/qianqi/Desktop/magenta/magenta/models/onsets_frames_transcription/onsets_frames_transcription_train.py", line 96, in run
    num_steps=FLAGS.num_steps)
  File "/home/qianqi/Desktop/magenta/magenta/models/onsets_frames_transcription/train_util.py", line 147, in train
    estimator.train(input_fn=transcription_data, max_steps=num_steps)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3089, in train
    rendezvous.raise_errors()
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train
    saving_listeners=saving_listeners)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1208, in _train_model_default
    saving_listeners)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1507, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 604, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1038, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 749, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1231, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1236, in _create_session
    return self._sess_creator.create_session()
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 909, in create_session
    hook.after_create_session(self.tf_sess, self.coord)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/util.py", line 86, in after_create_session
    session.run(self._initializer)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/qianqi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [No files matched pattern: ]
	 [[node list_files/assert_not_empty/Assert (defined at /Desktop/magenta/magenta/models/onsets_frames_transcription/data.py:589) ]]

Original stack trace for 'list_files/assert_not_empty/Assert':
  File "/anaconda3/envs/magenta/bin/onsets_frames_transcription_train", line 33, in <module>
    sys.exit(load_entry_point('magenta', 'console_scripts', 'onsets_frames_transcription_train')())
  File "/Desktop/magenta/magenta/models/onsets_frames_transcription/onsets_frames_transcription_train.py", line 123, in console_entry_point
    tf.app.run(main)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Desktop/magenta/magenta/models/onsets_frames_transcription/onsets_frames_transcription_train.py", line 118, in main
    additional_trial_info=additional_trial_info)
  File "/Desktop/magenta/magenta/models/onsets_frames_transcription/onsets_frames_transcription_train.py", line 96, in run
    num_steps=FLAGS.num_steps)
  File "/Desktop/magenta/magenta/models/onsets_frames_transcription/train_util.py", line 147, in train
    estimator.train(input_fn=transcription_data, max_steps=num_steps)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train
    saving_listeners=saving_listeners)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1201, in _train_model_default
    self._get_features_and_labels_from_input_fn(input_fn, ModeKeys.TRAIN))
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1037, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3041, in _call_input_fn
    return input_fn(**kwargs)
  File "/Desktop/magenta/magenta/models/onsets_frames_transcription/data.py", line 731, in provide_batch
    examples, is_training, shuffle_examples, skip_n_initial_records, hparams)
  File "/Desktop/magenta/magenta/models/onsets_frames_transcription/data.py", line 589, in read_examples
    generate_sharded_filenames(examples), shuffle=shuffle_examples)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2463, in list_files
    return DatasetV1Adapter(DatasetV2.list_files(file_pattern, shuffle, seed))
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1115, in list_files
    condition, [message], summarize=1, name="assert_not_empty")
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/util/tf_should_use.py", line 247, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 167, in Assert
    return gen_logging_ops._assert(condition, data, summarize, name="Assert")
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 63, in _assert
    name=name)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()
````

**Comment by cghawthorne** [comment]
There's a typo when you're defining the path to the tfrecord (extra `i`): `TRAIN_EXAMPLEiS='./maps_config2_test.tfrecord'`. Is that what's causing the problem?

**Comment by James-qq** [comment]
> There's a typo when you're defining the path to the tfrecord (extra `i`): `TRAIN_EXAMPLEiS='./maps_config2_test.tfrecord'`. Is that what's causing the problem?

OMG! That's it. Thank you very much!

**Comment by James-qq** [comment]
Then I encountered another problem. During my train time, my progress was killed by the system. My system version is ubuntu 20.04.
```
I0908 20:25:18.083855 140431052494592 transform.py:629] Created /tmp/tmpu_k00450.wav with effects: pitch contrast equalizer equalizer reverb
train.sh: line 7:  2988 Killed                  onsets_frames_transcription_train --examples_path="${TRAIN_EXAMPLES}" --model_dir="${RUN_DIR}" --mode='train'
```
My system log is as follows:
```
/var/log/kern.log:Sep  7 20:25:18 ubuntu kernel: [ 1559.596931] Out of memory: Killed process 2988 (onsets_frames_t) total-vm:8923132kB, anon-rss:4976568kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:14880kB oom_score_adj:0
```
My system's memory is just 4G, so at least how much memory is needed to run this train? My tfrecord file is 681MB.
