### ISSUE TITLE
Unicode Decode Error while trying to execute Music_VAE_train

### ISSUE THREAD

**Issue by IvanPopAudio** [magenta/magenta#1828]
Hello,

I'm trying to train Music_VAE model with a dataset that I used to train Melody_RNN. Using the same .tfrecord file, Music_VAE keeps giving the following error:
`
2020-09-30 15:45:39.282278: W tensorflow/core/framework/op_kernel.cc:1755] Invalid argument: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 1: 'utf-8' codec can't decode byte 0x84 in position 1: invalid start byte in field: magenta.NoteSequence.filename`

This error repeats several times for different bytes. I'm using Python 3.8 with the latest magenta distribution. Melody_RNN_train had no such errors and I was successful in training the model. 

Here is the full traceback of one of the errors: (They are all the same, except for the byte number)

```
Traceback (most recent call last):

  File "C:\Users\AlonZ\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\script_ops.py", line 242, in __call__
    return func(device, token, args)

  File "C:\Users\AlonZ\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\script_ops.py", line 131, in __call__
    ret = self._func(*args)

  File "C:\Users\AlonZ\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\autograph\impl\api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\AlonZ\AppData\Roaming\Python\Python38\site-packages\magenta\models\music_vae\data.py", line 1746, in _convert_and_pad
    item = converter.str_to_item_fn(item_str.numpy())  # pylint:disable=not-callable

  File "c:\users\alonz\appdata\roaming\python\python38\site-packages\google\protobuf\internal\python_message.py", line 812, in FromString
    message.MergeFromString(s)

  File "c:\users\alonz\appdata\roaming\python\python38\site-packages\google\protobuf\internal\python_message.py", line 1145, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:

  File "c:\users\alonz\appdata\roaming\python\python38\site-packages\google\protobuf\internal\python_message.py", line 1212, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)

  File "c:\users\alonz\appdata\roaming\python\python38\site-packages\google\protobuf\internal\decoder.py", line 619, in DecodeField
    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])

  File "c:\users\alonz\appdata\roaming\python\python38\site-packages\google\protobuf\internal\decoder.py", line 572, in _ConvertToUnicode
    value = local_unicode(byte_str, 'utf-8')
```

I found this thread: [Issue #1330 ](https://github.com/magenta/magenta/issues/1330) and it seems this issue should be resolved, but alas I'm still getting it.

Please let me know how I can fix it, and thank you for your help in advance.

**Comment by IvanPopAudio** [comment]
Update: So I tried to run the training with a different dataset - and it seems to work.

So the problem is with my original dataset - can anyone point out what I can change to make it work? It's a nice one.
