### ISSUE TITLE
Questions about the difference between different programs related to evaluation("Onsets and Frames")

### ISSUE THREAD

**Issue by guardian2020** [magenta/magenta#1839]
Hi!

I'm trying to replicate "Onsets and Frames" and evaluate on MAPS to get the paper's results. In the code provided in the branch 9885adef56, there are several programs for evaluation, specifically:
1. "eval" mode in onsets_frames_transcription_train.py (which refers to train_util.py)
2. "test" mode in onsets_frames_transcription_train.py (which refers to train_util.py)
3. onsets_frames_transcription_infer.py
4. onsets_frames_transcription_transcribe.py

There seems to be some slight differences between them. For example, in the "eval" or "test" mode of train_util.py, onsets seems not to be used in inference (which is required by the paper). In onsets_frames_transcription_infer.py, velocities seems to be used to calculate note metrics (which seems not involved in the paper)

Does anyone know the difference the "eval" and "test" mode of onsets_frames_transcription_train.py,  onsets_frames_transcription_infer.py and onsets_frames_transcription_transcribe.py?
If I'd like to evaluate under the same conditions as the paper, which program should I use and whether should I make some modifications to the code?
I ask this is because I used "eval" mode of onsets_frames_transcription_train.py with maps_config2_test.tfrecord. The values of the metrics (especially the frame-based metrics) seem to be **quite different** from the paper.

Thanks!

**Comment by cghawthorne** [comment]
The two big differences between the eval code and the infer.py code are that infer evaluates on the entire example and applies the post-processing steps. For comparison to the paper, you should use infer.py.

**Comment by nkjulia** [comment]
i encounter an  error as below  when use onsets_frames_transcription_train.py to evaluate on test data, is there any solution? thanks a lot

W0522 17:40:45.179362 140664331384576 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "./magenta/models/onsets_frames_transcription/onsets_frames_transcription_train_maestro.py", line 133, in <module>
    console_entry_point()
  File "./magenta/models/onsets_frames_transcription/onsets_frames_transcription_train_maestro.py", line 129, in console_entry_point
    tf.app.run(main)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "./magenta/models/onsets_frames_transcription/onsets_frames_transcription_train_maestro.py", line 124, in main
    additional_trial_info=additional_trial_info)
  File "./magenta/models/onsets_frames_transcription/onsets_frames_transcription_train_maestro.py", line 113, in run
    num_steps=FLAGS.eval_num_steps)
  File "/DATA/disk1/juliayang/magenta-master/magenta/models/onsets_frames_transcription/train_util.py", line 253, in evaluate
    checkpoint_path=checkpoint_path, name=name)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3151, in evaluate
    rendezvous.raise_errors()
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3146, in evaluate
    name=name)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 467, in evaluate
    name=name)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 510, in _actual_eval
    return _evaluate()
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 492, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1531, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1567, in _call_model_fn_eval
    config)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2962, in _call_model_fn
    config)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3220, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1729, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2072, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "/DATA/disk1/juliayang/magenta-master/magenta/models/onsets_frames_transcription/train_util.py", line 78, in wrapped_model_fn
    return model_fn(features, labels, mode, params, config)
  File "/DATA/disk1/juliayang/magenta-master/magenta/models/onsets_frames_transcription/model.py", line 420, in model_fn
    eval_metric_ops=metric_ops)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/model_fn.py", line 155, in __new__
    loss = _validate_estimator_spec_loss(loss, mode)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/model_fn.py", line 329, in _validate_estimator_spec_loss
    raise ValueError('Missing loss.')
ValueError: Missing loss.
