### ISSUE TITLE
Pianoroll RNN-NADE custom dataset sample generation error

### ISSUE THREAD

**Issue by acostarelli** [magenta/magenta#1878]
I trained my own Pianoroll model on my own dataset. I tried to generate output samples using this command:

```
pianoroll_rnn_nade_generate --run_dir=. --output_dir=. --num_outputs=5 --num_steps=128 --primer_pitches="[67,64,60]"
```
where the current directory I'm in consists only of a single folder `train/`. Inside this `train/` folder are the following files:

- checkpoint
- model.ckpt-6004.data-00000-of-00001
- model.ckpt-6004.index
- model.ckpt-6004.meta

This setup has worked for me with Polyphony RNN.

However, when I run the command above, it ultimately fails before generating any samples with this error:

```
I0113 10:59:32.182424 4516371904 saver.py:1293] Restoring parameters from ./train/model.ckpt-6004
Traceback (most recent call last):
  File "/Users/spameggs/opt/anaconda3/envs/magenta/bin/pianoroll_rnn_nade_generate", line 8, in <module>
    sys.exit(console_entry_point())
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/pianoroll_rnn_nade/pianoroll_rnn_nade_generate.py", line 250, in console_entry_point
    tf.app.run(main)
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/pianoroll_rnn_nade/pianoroll_rnn_nade_generate.py", line 245, in main
    run_with_flags(generator)
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/pianoroll_rnn_nade/pianoroll_rnn_nade_generate.py", line 208, in run_with_flags
    generated_sequence = generator.generate(primer_sequence, generator_options)
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/shared/sequence_generator.py", line 194, in generate
    return self._generate(input_sequence, generator_options)
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/pianoroll_rnn_nade/pianoroll_rnn_nade_sequence_generator.py", line 127, in _generate
    total_steps, pianoroll_seq, **args)
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/pianoroll_rnn_nade/pianoroll_rnn_nade_model.py", line 97, in generate_pianoroll_sequence
    steps_per_iteration=steps_per_iteration)
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/shared/events_rnn_model.py", line 378, in _generate_events
    steps_per_iteration=steps_per_iteration)
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/common/beam_search.py", line 130, in beam_search
    beam_entries, generate_step_fn, branch_factor, first_iteration_num_steps)
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/common/beam_search.py", line 63, in _generate_branches
    all_sequences, all_states, all_scores)
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/shared/events_rnn_model.py", line 232, in _generate_step
    temperature)
  File "/Users/spameggs/opt/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/pianoroll_rnn_nade/pianoroll_rnn_nade_model.py", line 74, in _generate_step_for_batch
    return final_state, loglik[:, 0]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

I did some experimenting and I found changing that list line to this:

```
return final_state, loglik
```

allowed the script to run without error. However, the generated MIDI files are all exactly identical each time I run the script (with the same checkpoint -- across different checkpoints, the output is different; but, for each checkpoint, the model always generates the same MIDI).

**Comment by aadarshb09** [comment]
Did you end up fixing this error? I have the same issue

**Comment by acostarelli** [comment]
No sorry.
