### ISSUE TITLE
Unpacking bundle script fails with NotFoundError

### ISSUE THREAD

**Issue by chmanie** [magenta/magenta#1906]
I'm trying to run the `unpack_bundle.py` script on a Mac w/ Python 3.7.7. I tried with `magenta` `v2.1.3` and `v1.3.2` with the same result:

```
python magenta/scripts/unpack_bundle.py --bundle-path '/Users/chris/Downloads/basic_rnn.mag' --checkpoint-path '/tmp/model.ckpt'
```

and am getting the following error:

```
/Users/chris/.pyenv/versions/3.7.7/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
/Users/chris/.pyenv/versions/3.7.7/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
WARNING:tensorflow:From /Users/chris/.pyenv/versions/3.7.7/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "magenta/scripts/unpack_bundle.py", line 48, in <module>
    tf.app.run()
  File "/Users/chris/.pyenv/versions/3.7.7/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/chris/.pyenv/versions/3.7.7/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/chris/.pyenv/versions/3.7.7/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "magenta/scripts/unpack_bundle.py", line 38, in main
    bundle = sequence_generator_bundle.read_bundle_file(bundle_file)
  File "/Users/chris/dev/ml/magenta/magenta/models/shared/sequence_generator_bundle.py", line 32, in read_bundle_file
    bundle.ParseFromString(f.read())
  File "/Users/chris/.pyenv/versions/3.7.7/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 117, in read
    self._preread_check()
  File "/Users/chris/.pyenv/versions/3.7.7/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory
```

Am I doing anything wrong here?

**Comment by cghawthorne** [comment]
The argument for the bundle should be `bundle_path`, not `bundle-path`.
