### ISSUE TITLE
Can't load GANSynth because File system scheme 'gs' not implemented

### ISSUE THREAD

**Issue by csestili** [magenta/magenta#1909]
Hi, I'm trying to load the GANSynth model in Python, and getting an error in `lib_model.Model.load_from_path()`.

Setup:
- GANSynth acoustic_only model downloaded and located at `models/acoustic_only/`

Code (minimal example):
```
from magenta.models.gansynth.lib import model as lib_model
import tensorflow.compat.v1 as tf
from magenta.models.gansynth.lib import flags as lib_flags

#CKPT_DIR = 'gs://magentadata/models/gansynth/acoustic_only'
CKPT_DIR = 'models/acoustic_only/'
BATCH_SIZE = 16

# Load the model
tf.reset_default_graph()
flags = lib_flags.Flags({
    'batch_size_schedule': [BATCH_SIZE],
    'tfds_data_dir': "gs://tfds-data/datasets",
})
model = lib_model.Model.load_from_path(CKPT_DIR, flags)
```

Traceback:
```
Traceback (most recent call last):
  File "gansynth.py", line 15, in <module>
    model = lib_model.Model.load_from_path(CKPT_DIR, flags)
  File "C:\Users\sesti\.virtualenvs\gan-synth-app-Z09H6cuh\lib\site-packages\magenta\models\gansynth\lib\model.py", line 178, in load_from_path
    model = cls(stage_id, batch_size, flags)
  File "C:\Users\sesti\.virtualenvs\gan-synth-app-Z09H6cuh\lib\site-packages\magenta\models\gansynth\lib\model.py", line 194, in __init__
    real_images, real_one_hot_labels = data_helper.provide_data(batch_size)
  File "C:\Users\sesti\.virtualenvs\gan-synth-app-Z09H6cuh\lib\site-packages\magenta\models\gansynth\lib\data_helpers.py", line 66, in provide_data
    dataset = self.dataset.provide_dataset()
  File "C:\Users\sesti\.virtualenvs\gan-synth-app-Z09H6cuh\lib\site-packages\magenta\models\gansynth\lib\datasets.py", line 118, in provide_dataset
    dataset = self._get_dataset_from_tfds()
  File "C:\Users\sesti\.virtualenvs\gan-synth-app-Z09H6cuh\lib\site-packages\magenta\models\gansynth\lib\datasets.py", line 69, in _get_dataset_from_tfds
    download=False)
  File "C:\Users\sesti\.virtualenvs\gan-synth-app-Z09H6cuh\lib\site-packages\tensorflow_datasets\core\load.py", line 325, in load
    dbuilder = builder(name, data_dir=data_dir, try_gcs=try_gcs, **builder_kwargs)
  File "C:\Users\sesti\.virtualenvs\gan-synth-app-Z09H6cuh\lib\site-packages\tensorflow_datasets\core\load.py", line 163, in builder                                                                                                                b = read_only_builder.builder_from_files(str(name), **builder_kwargs)                                                 File "C:\Users\sesti\.virtualenvs\gan-synth-app-Z09H6cuh\lib\site-packages\tensorflow_datasets\core\read_only_builder.py", line 155, in builder_from_files                                                                                        builder_dir = _find_builder_dir(name, **builder_kwargs)                                                               File "C:\Users\sesti\.virtualenvs\gan-synth-app-Z09H6cuh\lib\site-packages\tensorflow_datasets\core\read_only_builder.py", line 216, in _find_builder_dir                                                                                         config_name=config,                                                                                                   File "C:\Users\sesti\.virtualenvs\gan-synth-app-Z09H6cuh\lib\site-packages\tensorflow_datasets\core\read_only_builder.py", line 266, in _find_builder_dir_single_dir                                                                              version_str = _get_version_str(builder_dir, requested_version=version_str)                                            File "C:\Users\sesti\.virtualenvs\gan-synth-app-Z09H6cuh\lib\site-packages\tensorflow_datasets\core\read_only_builder.py", line 314, in _get_version_str                                                                                          all_versions = version_lib.list_all_versions(builder_dir)                                                             File "C:\Users\sesti\.virtualenvs\gan-synth-app-Z09H6cuh\lib\site-packages\tensorflow_datasets\core\utils\version.py", line 182, in list_all_versions                                                                                             if not tf.io.gfile.exists(root_dir):                                                                                  File "C:\Users\sesti\.virtualenvs\gan-synth-app-Z09H6cuh\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 268, in file_exists_v2                                                                                                      _pywrap_file_io.FileExists(compat.path_to_bytes(path))                                                              tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme 'gs' not implemented (file: 'gs://tfds-data/datasets\nsynth\gansynth_subset')
```

After some searching, it looks like `gs` is not implemented on Windows, and I'm using Windows 10, so that would explain this issue.

Is there some way I can work around this? I'm not sure why the dataset would need to be downloaded in order to load the model.

Thank you for your help!

**Comment by yitopeligo** [comment]
Same error for me too as I try to _gansynth_generate --ckpt_dir=acoustic_only --output_dir=output_ in command line.

**Comment by AnthonyFang623** [comment]
I've met the same error as you mister. Ddi you mix it? I have got no idea how to fix this bug, If you fix it, please tell me. Thank you very much!
