### ISSUE TITLE
COCONet ERROR run train_bazel.sh

### ISSUE THREAD

**Issue by YawYoung** [magenta/magenta#1914]
When I run `sh train_bazel.sh`, I encountered this problem
```
ValueError: The initializer passed is not valid. It should be a callable with no arguments and the shape should not be provided or an instance of `tf.keras.initializers.*' and `shape` should be fully defined.
```
Full log:
```
Traceback (most recent call last):
  File "coconet_train.py", line 382, in <module>
    tf.app.run()
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "coconet_train.py", line 263, in main
    m = lib_graph.build_graph(is_training=True, hparams=hparams)
  File "/data/1-Project-2021/boya/magenta/models/coconet/lib_graph.py", line 404, in build_graph
    use_placeholders=use_placeholders)
  File "/data/1-Project-2021/boya/magenta/models/coconet/lib_graph.py", line 47, in __init__
    self.build()
  File "/data/1-Project-2021/boya/magenta/models/coconet/lib_graph.py", line 98, in build
    featuremaps = self.apply_convolution(featuremaps, layer, i)
  File "/data/1-Project-2021/boya/magenta/models/coconet/lib_graph.py", line 296, in apply_convolution
    pointwise_initializer=initializer if self.is_training else None)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/keras/legacy_tf_layers/convolutional.py", line 1096, in separable_conv2d
    return layer.apply(inputs)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 1701, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/keras/legacy_tf_layers/base.py", line 547, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 757, in __call__
    self._maybe_build(inputs)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 2098, in _maybe_build
    self.build(input_shapes)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py", line 1805, in build
    dtype=self.dtype)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/keras/legacy_tf_layers/base.py", line 460, in add_weight
    **kwargs)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 448, in add_weight
    caching_device=caching_device)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 750, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1572, in get_variable
    aggregation=aggregation)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1315, in get_variable
    aggregation=aggregation)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 569, in get_variable
    aggregation=aggregation)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 521, in _true_getter
    aggregation=aggregation)
  File "/data/1-Project-2021/venv/magenta_dev/lib64/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 919, in _get_single_variable
    raise ValueError("The initializer passed is not valid. It should "
ValueError: The initializer passed is not valid. It should be a callable with no arguments and the shape should not be provided or an instance of `tf.keras.initializers.*' and `shape` should be fully defined.
```
Related issue: 
https://github.com/magenta/magenta/pull/1901/commits/f2559da66ce4435a8d3a8e17dd1e4fb18508151d
ENV: TensorFlow 2.3

**Comment by illuminatedjavascript** [comment]
Having the same issue. Any updates on the outcome/resolution before closure?

**Comment by zoe-dataroots** [comment]
With which version of TF and Python did you made the training work? It does not work with TF version 2.3.0 for me.
