### ISSUE TITLE
onsets and frames problems when eval mode

### ISSUE THREAD

**Issue by nkjulia** [magenta/magenta#1919]
hi i try to use onsets_frames_transcription_train.py and eval mode to output metrics on test data , but i got this error , is there anyone can help ? thanks~

INFO:tensorflow:evaluation_loop marked as finished
I0524 11:21:34.920045 140096573208320 error_handling.py:115] evaluation_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0524 11:21:34.920181 140096573208320 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "magenta/models/onsets_frames_transcription/onsets_frames_transcription_train_maestro.py", line 133, in <module>
    console_entry_point()
  File "magenta/models/onsets_frames_transcription/onsets_frames_transcription_train_maestro.py", line 129, in console_entry_point
    tf.app.run(main)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "magenta/models/onsets_frames_transcription/onsets_frames_transcription_train_maestro.py", line 124, in main
    additional_trial_info=additional_trial_info)
  File "magenta/models/onsets_frames_transcription/onsets_frames_transcription_train_maestro.py", line 113, in run
    num_steps=FLAGS.eval_num_steps)
  File "/DATA/disk1/juliayang/magenta-master/magenta/models/onsets_frames_transcription/train_util.py", line 253, in evaluate
    checkpoint_path=checkpoint_path, name=name)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3151, in evaluate
    rendezvous.raise_errors()
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3146, in evaluate
    name=name)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 467, in evaluate
    name=name)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 510, in _actual_eval
    return _evaluate()
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 492, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1531, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1567, in _call_model_fn_eval
    config)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2962, in _call_model_fn
    config)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3220, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1729, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2072, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "/DATA/disk1/juliayang/magenta-master/magenta/models/onsets_frames_transcription/train_util.py", line 78, in wrapped_model_fn
    return model_fn(features, labels, mode, params, config)
  File "/DATA/disk1/juliayang/magenta-master/magenta/models/onsets_frames_transcription/model.py", line 420, in model_fn
    eval_metric_ops=metric_ops)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/model_fn.py", line 155, in __new__
    loss = _validate_estimator_spec_loss(loss, mode)
  File "/DATA/disk1/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/model_fn.py", line 329, in _validate_estimator_spec_loss
    raise ValueError('Missing loss.')
ValueError: Missing loss.

**Comment by cghawthorne** [comment]
Hi @nkjulia, it looks like you're using a custom script to set up model training (`onsets_frames_transcription_train_maestro.py`), so I'm not sure what all is going on. Does training work with the standard script?

**Comment by nkjulia** [comment]
> Hi @nkjulia, it looks like you're using a custom script to set up model training (`onsets_frames_transcription_train_maestro.py`), so I'm not sure what all is going on. Does training work with the standard script?

it's no different with the standard script  , i just rename it,  training  works  well ....

**Comment by cghawthorne** [comment]
Hmm, perhaps something changed with a recent version of TensorFlow. We do leave the loss as None during eval: https://github.com/magenta/magenta/blob/master/magenta/models/onsets_frames_transcription/model.py#L375

You could try changing that so that `loss = tf.losses.get_total_loss()` for both train and eval mode and see if that works.

**Comment by nkjulia** [comment]
> Hmm, perhaps something changed with a recent version of TensorFlow. We do leave the loss as None during eval: https://github.com/magenta/magenta/blob/master/magenta/models/onsets_frames_transcription/model.py#L375
> 
> You could try changing that so that `loss = tf.losses.get_total_loss()` for both train and eval mode and see if that works.

i made the changes as you mentioned, it works. 
thank u.

**Comment by cghawthorne** [comment]
Glad to hear that it worked for you. Would you mind sending a PR with your fix?
