### ISSUE TITLE
Coconet: ValueError running train_bazel.sh

### ISSUE THREAD

**Issue by malcolmsailor** [magenta/magenta#1950]
When attempting to run `train_bazel.sh`, I get the following error:

`ValueError: The initializer passed is not valid. It should be a callable with no arguments and the shape should not be provided or an instance of `tf.keras.initializers.*' and `shape` should be fully defined.`

#1914 was opened for this same issue but the opener closed it immediately afterwards. The changes in https://github.com/magenta/magenta/commit/f2559da66ce4435a8d3a8e17dd1e4fb18508151d, which they referenced in their question, doesn't seem to have resolved this issue for me.

Here is the full traceback:

```
Traceback (most recent call last):
  File "coconet_train.py", line 382, in <module>
    tf.app.run()
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "coconet_train.py", line 263, in main
    m = lib_graph.build_graph(is_training=True, hparams=hparams)
  File "/Volumes/Frescobaldi/third_party_ml_stuff/magenta/magenta/models/coconet/lib_graph.py", line 401, in build_graph
    use_placeholders=use_placeholders)
  File "/Volumes/Frescobaldi/third_party_ml_stuff/magenta/magenta/models/coconet/lib_graph.py", line 47, in __init__
    self.build()
  File "/Volumes/Frescobaldi/third_party_ml_stuff/magenta/magenta/models/coconet/lib_graph.py", line 98, in build
    featuremaps = self.apply_convolution(featuremaps, layer, i)
  File "/Volumes/Frescobaldi/third_party_ml_stuff/magenta/magenta/models/coconet/lib_graph.py", line 293, in apply_convolution
    pointwise_initializer=initializer if self.is_training else None)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/keras/legacy_tf_layers/convolutional.py", line 1432, in separable_conv2d
    return layer.apply(inputs)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/keras/engine/base_layer_v1.py", line 1679, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/keras/legacy_tf_layers/base.py", line 567, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/keras/engine/base_layer_v1.py", line 745, in __call__
    self._maybe_build(inputs)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/keras/engine/base_layer_v1.py", line 2068, in _maybe_build
    self.build(input_shapes)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/keras/layers/convolutional.py", line 1840, in build
    dtype=self.dtype)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/keras/legacy_tf_layers/base.py", line 466, in add_weight
    **kwargs)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/keras/engine/base_layer_v1.py", line 440, in add_weight
    caching_device=caching_device)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 818, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1595, in get_variable
    aggregation=aggregation)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1338, in get_variable
    aggregation=aggregation)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 593, in get_variable
    aggregation=aggregation)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 545, in _true_getter
    aggregation=aggregation)
  File "/Volumes/Frescobaldi/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 942, in _get_single_variable
    raise ValueError("The initializer passed is not valid. It should "
ValueError: The initializer passed is not valid. It should be a callable with no arguments and the shape should not be provided or an instance of `tf.keras.initializers.*' and `shape` should be fully defined.
```

**Comment by malcolmsailor** [comment]
I believe I did eventually get it to run, but I'm afraid to say I no longer recall precisely what I did. Possibly it involved using an older version of tensorflow in the virtual environment. Best of luck.
