### ISSUE TITLE
score2perf trains but fails on eval

### ISSUE THREAD

**Issue by almostimplemented** [magenta/magenta#1999]
Currently running [score2perf](https://github.com/magenta/magenta/tree/main/magenta/models/score2perf) training. I hit an error that other users have cited (https://github.com/tensorflow/tensor2tensor/issues/1869). 

Basically, training works fine:
```
I0517 11:43:28.406037 140246740100928 session_manager.py:527] Running local_init_op.
I0517 11:43:28.494832 140246740100928 session_manager.py:530] Done running local_init_op.
I0517 11:43:31.852125 140246740100928 basic_session_run_hooks.py:629] Calling checkpoint listeners before saving checkpoint 0...
I0517 11:43:31.876228 140246740100928 basic_session_run_hooks.py:633] Saving checkpoints for 0 into /homes/ace01/forks/magenta/train_dir/model.ckpt.
I0517 11:43:34.053229 140246740100928 basic_session_run_hooks.py:641] Calling checkpoint listeners after saving checkpoint 0...
2022-05-17 11:43:38.160326: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
I0517 11:43:39.361764 140246740100928 basic_session_run_hooks.py:266] loss = 9.503252, step = 0
I0517 11:43:54.692961 140246740100928 basic_session_run_hooks.py:717] global_step/sec: 6.51378
I0517 11:43:54.708777 140246740100928 basic_session_run_hooks.py:264] loss = 5.61629, step = 100 (15.347 sec)
I0517 11:44:04.470936 140246740100928 basic_session_run_hooks.py:717] global_step/sec: 10.227
I0517 11:44:04.472368 140246740100928 basic_session_run_hooks.py:264] loss = 4.7884755, step = 200 (9.764 sec)
```

But then it fails to instantiate the model for evaluation:
```
I0517 11:45:23.869750 140246740100928 basic_session_run_hooks.py:641] Calling checkpoint listeners after saving checkpoint 1000...
I0517 11:45:23.884094 140246740100928 problem.py:653] Reading data files from /homes/ace01/forks/magenta/jazz_piano_datagen/score2perf_jazz_piano_language_uncropped_aug-dev*
...
I0517 11:45:27.860735 140246740100928 saver.py:1395] Restoring parameters from /homes/ace01/forks/magenta/train_dir/model.ckpt-1000
2022-05-17 11:45:28.132465: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at save_restore_v2_ops.cc:222 : NOT_FOUND: Key transformer/parallel_0_3/transformer/transformer/body/decoder/layer_0/self_attention/multihead_attention/k/kernel not found in checkpoint
Traceback (most recent call last):
  File "/homes/ace01/forks/magenta/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1377, in _do_call
    return fn(*args)
  File "/homes/ace01/forks/magenta/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1361, in _run_fn
    target_list, run_metadata)
  File "/homes/ace01/forks/magenta/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1455, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) NOT_FOUND: Key transformer/parallel_0_3/transformer/transformer/body/decoder/layer_0/self_attention/multihead_attention/k/kernel not found in checkpoint
	 [[{{node save/RestoreV2_1}}]]
	 [[save/RestoreV2/_1]]
  (1) NOT_FOUND: Key transformer/parallel_0_3/transformer/transformer/body/decoder/layer_0/self_attention/multihead_attention/k/kernel not found in checkpoint
	 [[{{node save/RestoreV2_1}}]]
0 successful operations.
0 derived errors ignored.
```

Full logs here:
[score2perf_error_logs.txt](https://github.com/magenta/magenta/files/8707600/score2perf_error_logs.txt)
 
`pip list` output:
[pip_list.txt](https://github.com/magenta/magenta/files/8707649/pip_list.txt)

**Comment by almostimplemented** [comment]
Possibly dupe of the still open #1862 , will try ToT tensor2tensor
