### ISSUE TITLE
Urgent : Unable to install magenta in windows Virtual env

### ISSUE THREAD

**Issue by Subham-create** [magenta/magenta#2024]
Hi All, 
Am trying to work on a project and tried installing magenta inside a virtual env as well as in conda environment and getting error as shown below:

Running setup.py install for llvmlite did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      running install
      running build
      got version from file C:\Users\subham_sharma\AppData\Local\Temp\2\pip-install-pqbdczc6\llvmlite_bf1602df11264046810d54e587c82f1a\llvmlite/_version.py {'version': '0.32.1', 'full': 'aa11b129c0b55973067422397821ae6d44fa5e70'}
      running build_ext
      C:\Users\subham_sharma\windows\Scripts\python.exe C:\Users\subham_sharma\AppData\Local\Temp\2\pip-install-pqbdczc6\llvmlite_bf1602df11264046810d54e587c82f1a\ffi\build.py
      -- Selecting Windows SDK version  to target Windows 10.0.20348.
      CMake Error at CMakeLists.txt:3 (project):
        Failed to run MSBuild command:

          MSBuild.exe

        to get the value of VCTargetsPath:

          The system cannot find the file specified

      -- Configuring incomplete, errors occurred!
      See also "C:/Users/subham_sharma/AppData/Local/Temp/2/tmpr4y108yd/CMakeFiles/CMakeOutput.log".
      CMake Error at CMakeLists.txt:3 (project):
        Generator

          Visual Studio 15 2017 Win64

        could not find any instance of Visual Studio.

      -- Configuring incomplete, errors occurred!
      See also "C:/Users/subham_sharma/AppData/Local/Temp/2/tmpmkb_iqk7/CMakeFiles/CMakeOutput.log".
      Trying generator 'Visual Studio 14 2015 Win64'
      Trying generator 'Visual Studio 15 2017 Win64'
      Traceback (most recent call last):
        File "C:\Users\subham_sharma\AppData\Local\Temp\2\pip-install-pqbdczc6\llvmlite_bf1602df11264046810d54e587c82f1a\ffi\build.py", line 192, in <module>
          main()
        File "C:\Users\subham_sharma\AppData\Local\Temp\2\pip-install-pqbdczc6\llvmlite_bf1602df11264046810d54e587c82f1a\ffi\build.py", line 180, in main
          main_win32()
        File "C:\Users\subham_sharma\AppData\Local\Temp\2\pip-install-pqbdczc6\llvmlite_bf1602df11264046810d54e587c82f1a\ffi\build.py", line 89, in main_win32
          generator = find_win32_generator()
        File "C:\Users\subham_sharma\AppData\Local\Temp\2\pip-install-pqbdczc6\llvmlite_bf1602df11264046810d54e587c82f1a\ffi\build.py", line 85, in find_win32_generator
          raise RuntimeError("No compatible cmake generator installed on this machine")
      RuntimeError: No compatible cmake generator installed on this machine
      error: command 'C:\\Users\\subham_sharma\\windows\\Scripts\\python.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> llvmlite

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

Any help or guidance would be appreciated!!

**Comment by Luka27** [comment]
@Subham-create I have the same issue! Could you solve this issue yet? I tried downgrading magenta and the other packages throwing errors, installing visual studio (working on pycharm), installing windows sdk, using another device and so on... It didn't help at all, unfortunately. If you have solved this issue I would be very grateful if you could send me instructions how to solve this, thank you :)
