### ISSUE TITLE
Errors when trying to install magenta

### ISSUE THREAD

**Issue by Luka27** [magenta/magenta#2031]
I get error messages for building wheels in various moduls (llvmlite, numba, python-rtmidi).
I'm using Python 3.9, already tried to reinstall everything, installed other package versions. It just doesn't work. Can you help me please?

(I removed some not so important code to not exceed the max. char. length here)

```
Building wheels for collected packages: numba, python-rtmidi, llvmlite
  Building wheel for numba (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [826 lines of output]
      TBB not found
      OpenMP disabled
      running bdist_wheel
      running build
      got version from file C:\Users\Dell\AppData\Local\Temp\pip-install-s_n9pbef\numba_9c8741e8713142ffb7ba6d62968ea471\numba/_version.py {'version': '0.49.1', 'full': 'd2cac8597ad2aa4074147d9c7595f5b5e9919901'}
      running build_py
      creating build
    
      running build_ext
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      building 'numba._dynfunc' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  Building wheel for python-rtmidi (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\rtmidi
      copying rtmidi\midiconstants.py -> build\lib.win-amd64-cpython-39\rtmidi
      copying rtmidi\midiutil.py -> build\lib.win-amd64-cpython-39\rtmidi
      copying rtmidi\release.py -> build\lib.win-amd64-cpython-39\rtmidi
      copying rtmidi\__init__.py -> build\lib.win-amd64-cpython-39\rtmidi
      running build_ext
      building 'rtmidi._rtmidi' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-rtmidi
  Running setup.py clean for python-rtmidi
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      running bdist_wheel
      C:\Users\Dell\anaconda3\python.exe C:\Users\Dell\AppData\Local\Temp\pip-install-s_n9pbef\llvmlite_4ce3f81337d447c18fde83ea427f20d5\ffi\build.py
      -- Selecting Windows SDK version  to target Windows 10.0.19044.
      CMake Error at CMakeLists.txt:3 (project):
        Failed to run MSBuild command:

          MSBuild.exe

        to get the value of VCTargetsPath:

          Das System kann die angegebene Datei nicht finden



      -- Configuring incomplete, errors occurred!
      See also "C:/Users/Dell/AppData/Local/Temp/tmp_9vh8mbn/CMakeFiles/CMakeOutput.log".
      CMake Error at CMakeLists.txt:3 (project):
        Generator

          Visual Studio 15 2017 Win64

        could not find any instance of Visual Studio.



      -- Configuring incomplete, errors occurred!
      See also "C:/Users/Dell/AppData/Local/Temp/tmp5dfq2vh1/CMakeFiles/CMakeOutput.log".
      Trying generator 'Visual Studio 14 2015 Win64'
      Trying generator 'Visual Studio 15 2017 Win64'
      Traceback (most recent call last):
        File "C:\Users\Dell\AppData\Local\Temp\pip-install-s_n9pbef\llvmlite_4ce3f81337d447c18fde83ea427f20d5\ffi\build.py", line 192, in <module>
          main()
        File "C:\Users\Dell\AppData\Local\Temp\pip-install-s_n9pbef\llvmlite_4ce3f81337d447c18fde83ea427f20d5\ffi\build.py", line 180, in main
          main_win32()
        File "C:\Users\Dell\AppData\Local\Temp\pip-install-s_n9pbef\llvmlite_4ce3f81337d447c18fde83ea427f20d5\ffi\build.py", line 89, in main_win32
          generator = find_win32_generator()
        File "C:\Users\Dell\AppData\Local\Temp\pip-install-s_n9pbef\llvmlite_4ce3f81337d447c18fde83ea427f20d5\ffi\build.py", line 85, in find_win32_generator
          raise RuntimeError("No compatible cmake generator installed on this machine")
      RuntimeError: No compatible cmake generator installed on this machine
      error: command 'C:\\Users\\Dell\\anaconda3\\python.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build numba python-rtmidi llvmlite
Installing collected packages: python-rtmidi, pygtrie, mido, llvmlite, keras, flatbuffers, tensorflow-estimator, sox, scipy, protobuf, promise, numba, keras-preprocessing, importlib_resources, imageio, etils, absl-py, tf-slim, tensorflow-probability, sk-video, resampy, mir-eval, matplotlib, googleapis-common-protos, dm-sonnet, tensorflow-metadata, librosa, tensorflow-datasets, tensorboard, note-seq, tensorflow, magenta
  Attempting uninstall: python-rtmidi
    Found existing installation: python-rtmidi 1.4.9
    Uninstalling python-rtmidi-1.4.9:
      Successfully uninstalled python-rtmidi-1.4.9
  Running setup.py install for python-rtmidi ... error
  error: subprocess-exited-with-error

  × Running setup.py install for python-rtmidi did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running install
      C:\Users\Dell\anaconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\rtmidi
      copying rtmidi\midiconstants.py -> build\lib.win-amd64-cpython-39\rtmidi
      copying rtmidi\midiutil.py -> build\lib.win-amd64-cpython-39\rtmidi
      copying rtmidi\release.py -> build\lib.win-amd64-cpython-39\rtmidi
      copying rtmidi\__init__.py -> build\lib.win-amd64-cpython-39\rtmidi
      running build_ext
      building 'rtmidi._rtmidi' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of python-rtmidi
  Moving to c:\users\dell\anaconda3\lib\site-packages\python_rtmidi-1.4.9.dist-info\
   from C:\Users\Dell\anaconda3\Lib\site-packages\~ython_rtmidi-1.4.9.dist-info
  Moving to c:\users\dell\anaconda3\lib\site-packages\rtmidi\
   from C:\Users\Dell\anaconda3\Lib\site-packages\~tmidi
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> python-rtmidi

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by suchdeep** [comment]
Hey @Luka27 I was facing a similar issue, but on Mac OS Big Sur version 11.6.
The thing that helped me resolve was to use python 3.7 instead of 3.9. I think that maybe helpful in your case too.
Also I had to manually install the JACK driver, you can find it here: https://jackaudio.org/downloads/

I hope this helps.

**Comment by Theodoridis** [comment]
> Hey @Luka27 I was facing a similar issue, but on Mac OS Big Sur version 11.6. The thing that helped me resolve was to use python 3.7 instead of 3.9. I think that maybe helpful in your case too. Also I had to manually install the JACK driver, you can find it here: https://jackaudio.org/downloads/
> 
> I hope this helps.

I have done as you recommend but I also encounter the same errors. I am on Ubuntu, have tried both python3.9 and python3.7 in venv without success despite the other required packages being installed.

Do you have any other recommendations I could try? I'm really keen to get this up and running.

My error is slightly different to that of the OP:
```
DEPRECATION: python-rtmidi is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for python-rtmidi ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for python-rtmidi did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.7
      creating build/lib.linux-x86_64-3.7/rtmidi
      copying rtmidi/__init__.py -> build/lib.linux-x86_64-3.7/rtmidi
      copying rtmidi/midiconstants.py -> build/lib.linux-x86_64-3.7/rtmidi
      copying rtmidi/release.py -> build/lib.linux-x86_64-3.7/rtmidi
      copying rtmidi/midiutil.py -> build/lib.linux-x86_64-3.7/rtmidi
      running build_ext
      building 'rtmidi._rtmidi' extension
      creating build/temp.linux-x86_64-3.7
      creating build/temp.linux-x86_64-3.7/src
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc -I/home/freqee/musicgen/magenta-env/include -I/usr/include/python3.7m -c src/_rtmidi.cpp -o build/temp.linux-x86_64-3.7/src/_rtmidi.o
      src/_rtmidi.cpp:39:10: fatal error: Python.h: No such file or directory
         39 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> python-rtmidi
```
