### ISSUE TITLE
Onsets and Frames Drums - Error in Inference

### ISSUE THREAD

**Issue by bgenchel** [magenta/magenta#2046]
In the inference square of the [collab notebook ](https://colab.research.google.com/notebooks/magenta/onsets_frames_transcription/onsets_frames_transcription.ipynb), I get the following error: 

```
WARNING:tensorflow:Reraising captured error
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/tensorflow/python/client/session.py](https://localhost:8080/#) in _do_call(self, fn, *args)
   1377     try:
-> 1378       return fn(*args)
   1379     except errors.OpError as e:

15 frames
InvalidArgumentError: TypeError: melspectrogram() takes 0 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/ops/script_ops.py", line 267, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/magenta/models/onsets_frames_transcription/data.py", line 118, in wav_to_spec
    spec = _wav_to_mel(wav_audio, hparams)

  File "/usr/local/lib/python3.8/dist-packages/magenta/models/onsets_frames_transcription/data.py", line 79, in _wav_to_mel
    mel = librosa.feature.melspectrogram(

TypeError: melspectrogram() takes 0 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given


	 [[{{node wav_to_spec}}]]
	 [[IteratorGetNext]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/tensorflow/python/client/session.py](https://localhost:8080/#) in _do_call(self, fn, *args)
   1395                     '\nsession_config.graph_options.rewrite_options.'
   1396                     'disable_meta_optimizer = True')
-> 1397       raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
   1398 
   1399   def _extend_graph(self):

InvalidArgumentError: Graph execution error:

TypeError: melspectrogram() takes 0 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/ops/script_ops.py", line 267, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/magenta/models/onsets_frames_transcription/data.py", line 118, in wav_to_spec
    spec = _wav_to_mel(wav_audio, hparams)

  File "/usr/local/lib/python3.8/dist-packages/magenta/models/onsets_frames_transcription/data.py", line 79, in _wav_to_mel
    mel = librosa.feature.melspectrogram(

TypeError: melspectrogram() takes 0 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given


	 [[{{node wav_to_spec}}]]
	 [[IteratorGetNext]]
```
In order to get to this step in the notebook, I had to use the fix described [here](https://github.com/magenta/magenta/issues/2045), so perhaps it was caused by the difference in the imports / package versions?

**Comment by turian** [comment]
I also have this issue

**Comment by turian** [comment]
This is due to librosa later versions forcing you to name your parameters.

A workaround is to edit `/usr/local/lib/python3.10/dist-packages/librosa/feature/spectral.py`

And comment out this line:

```
def melspectrogram(
    #*,
    y: Optional[np.ndarray] = None,
```
