### ISSUE TITLE
Stuck at Gdrive mounted

### ISSUE THREAD

**Issue by Adimysk** [magenta/magenta#2071]
Im trying to train my own model but when i sign into google collab it loads everything just fine but gives me an error telling me it cant find the .zip of the name of the instrument i just made. so i refresh and it just hangs out at Using a Tesla T4 GPU...
Mounting Google Drive...
Mounted at gdrive

**Comment by Adimysk** [comment]
pying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_destroyer_saw_F.wav to audio/KOAN_SOUND_bass_destroyer_saw_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_wet_filter_02_F.wav to audio/KOAN_SOUND_bass_wet_filter_02_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_pitch_punch_02_Eb.wav to audio/KOAN_SOUND_bass_pitch_punch_02_Eb.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_dirt_hit_02_Eb.wav to audio/KOAN_SOUND_bass_dirt_hit_02_Eb.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_100_bass_loop_tech_bounce_02_F.wav to audio/KOAN_SOUND_100_bass_loop_tech_bounce_02_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_wet_n_wide_03_Eb.wav to audio/KOAN_SOUND_bass_wet_n_wide_03_Eb.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_pitch_punch_03_Eb.wav to audio/KOAN_SOUND_bass_pitch_punch_03_Eb.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_pitch_punch_08_F.wav to audio/KOAN_SOUND_bass_pitch_punch_08_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_86_bass_loop_square_fuzz_F.wav to audio/KOAN_SOUND_86_bass_loop_square_fuzz_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_pitch_punch_07_F.wav to audio/KOAN_SOUND_bass_pitch_punch_07_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_wet_n_wide_04_F.wav to audio/KOAN_SOUND_bass_wet_n_wide_04_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_wet_filter_01_Eb.wav to audio/KOAN_SOUND_bass_wet_filter_01_Eb.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_neuro_stab_07_F.wav to audio/KOAN_SOUND_bass_neuro_stab_07_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_pitch_punch_04_F.wav to audio/KOAN_SOUND_bass_pitch_punch_04_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_verb_reese_F.wav to audio/KOAN_SOUND_bass_verb_reese_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_neuro_stab_04_Eb.wav to audio/KOAN_SOUND_bass_neuro_stab_04_Eb.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_noisy_reese_01_F.wav to audio/KOAN_SOUND_bass_noisy_reese_01_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_square_fuzz_F.wav to audio/KOAN_SOUND_bass_square_fuzz_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_pitch_punch_06_F.wav to audio/KOAN_SOUND_bass_pitch_punch_06_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_dirt_hit_01_Eb.wav to audio/KOAN_SOUND_bass_dirt_hit_01_Eb.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_86_bass_loop_chunk_chop_01_F.wav to audio/KOAN_SOUND_86_bass_loop_chunk_chop_01_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_thick_saw_03_F.wav to audio/KOAN_SOUND_bass_thick_saw_03_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_86_bass_loop_mid_square_F.wav to audio/KOAN_SOUND_86_bass_loop_mid_square_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_thick_saw_05_F.wav to audio/KOAN_SOUND_bass_thick_saw_05_F.wav
Copying /content/gdrive/MyDrive/allshiz/Just bass/KOAN_SOUND_bass_pitch_punch_01_Eb.wav to audio/KOAN_SOUND_bass_pitch_punch_01_Eb.wav
Preparing new dataset from `audio/`

Creating dataset...
This usually takes around 2-3 minutes for each minute of audio
(10 minutes of training audio -> 20-30 minutes)

Training...
2023-08-25 06:51:20.227175: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.10/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-08-25 06:51:20.227309: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.10/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-08-25 06:51:20.227330: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/usr/local/bin/ddsp_run", line 5, in <module>
    from ddsp.training.ddsp_run import console_entry_point
  File "/usr/local/lib/python3.10/dist-packages/ddsp/__init__.py", line 21, in <module>
    from ddsp import losses
  File "/usr/local/lib/python3.10/dist-packages/ddsp/losses.py", line 23, in <module>
    from ddsp import spectral_ops
  File "/usr/local/lib/python3.10/dist-packages/ddsp/spectral_ops.py", line 25, in <module>
    import tensorflow_probability as tfp
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/__init__.py", line 20, in <module>
    from tensorflow_probability import substrates
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/substrates/__init__.py", line 17, in <module>
    from tensorflow_probability.python.internal import all_util
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/__init__.py", line 138, in <module>
    dir(globals()[pkg_name])  # Forces loading the package from its lazy loader.
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/internal/lazy_loader.py", line 57, in __dir__
    module = self._load()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/internal/lazy_loader.py", line 37, in _load
    self._on_first_access()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/__init__.py", line 59, in _validate_tf_environment
    raise ImportError(
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.12; Detected an installation of version 2.11.1. Please upgrade TensorFlow to proceed.

Exporting model...
2023-08-25 06:51:24.279297: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.10/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-08-25 06:51:24.279423: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.10/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-08-25 06:51:24.279448: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/usr/local/bin/ddsp_export", line 5, in <module>
    from ddsp.training.ddsp_export import console_entry_point
  File "/usr/local/lib/python3.10/dist-packages/ddsp/__init__.py", line 21, in <module>
    from ddsp import losses
  File "/usr/local/lib/python3.10/dist-packages/ddsp/losses.py", line 23, in <module>
    from ddsp import spectral_ops
  File "/usr/local/lib/python3.10/dist-packages/ddsp/spectral_ops.py", line 25, in <module>
    import tensorflow_probability as tfp
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/__init__.py", line 20, in <module>
    from tensorflow_probability import substrates
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/substrates/__init__.py", line 17, in <module>
    from tensorflow_probability.python.internal import all_util
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/__init__.py", line 138, in <module>
    dir(globals()[pkg_name])  # Forces loading the package from its lazy loader.
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/internal/lazy_loader.py", line 57, in __dir__
    module = self._load()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/internal/lazy_loader.py", line 37, in _load
    self._on_first_access()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/__init__.py", line 59, in _validate_tf_environment
    raise ImportError(
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.12; Detected an installation of version 2.11.1. Please upgrade TensorFlow to proceed.
Export complete! Zipping /content/gdrive/MyDrive/allshiz/Just bass/ddsp-training-2023-08-24-2337/Koan to /content/gdrive/MyDrive/allshiz/Just bass/ddsp-training-2023-08-24-2337/Koan.zip
	zip warning: name not matched: ./Koan

zip error: Nothing to do! (try: zip -r Koan.zip . -i ./Koan)
Zipping Complete! Downloading... Koan.zip
You can also find your model at /content/gdrive/MyDrive/allshiz/Just bass/ddsp-training-2023-08-24-2337/Koan
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ipyfilechooser/filechooser.py](https://localhost:8080/#) in _on_select_click(self, _b)
    315             if self._callback is not None:
    316                 try:
--> 317                     self._callback(self)
    318                 except TypeError:
    319                     # Support previous behaviour of not passing self

3 frames
[/usr/local/lib/python3.10/dist-packages/google/colab/files.py](https://localhost:8080/#) in download(filename)
    223   if not _os.path.exists(filename):
    224     msg = 'Cannot find file: {}'.format(filename)
--> 225     raise FileNotFoundError(msg)  # pylint: disable=undefined-variable
    226 
    227   comm_manager = _IPython.get_ipython().kernel.comm_manager

FileNotFoundError: Cannot find file: /content/gdrive/MyDrive/allshiz/Just bass/ddsp-training-2023-08-24-2337/Koan.zip
