### ISSUE TITLE
magenta installing

### ISSUE THREAD

**Issue by omrii12** [magenta/magenta#2093]
Im trying to install magenta using conda and I get errors every time. (Mac m1)

**Comment by teobaldo33** [comment]
Im also struggling

i installed numba with conda. It solved some issues.

I managed installing all dependencies doing this(i think thats what i did, tried a bunch of stuff) :
```
conda install numba
pip install llvmlite==0.39.1 magenta
```

but i have error with numpy version when i try to generate a sequence for example.

**Comment by teobaldo33** [comment]
I uninstalled numpy then redid :
pip install llvmlite==0.39.1 magenta

it installed all dependencies.

now i get this error : 
```
convert_dir_to_note_sequences \
  --input_dir=/Users/theotenaguillo/workspace/magenta/magenta-bach/bach-midi-collection \
  --output_file=tmp/notesequences.tfrecord \
  --recursive
Traceback (most recent call last):
  File "/Users/theotenaguillo/miniforge3/envs/magenta/bin/convert_dir_to_note_sequences", line 5, in <module>
    from magenta.scripts.convert_dir_to_note_sequences import console_entry_point
  File "/Users/theotenaguillo/miniforge3/envs/magenta/lib/python3.8/site-packages/magenta/__init__.py", line 17, in <module>
    import magenta.common.beam_search
  File "/Users/theotenaguillo/miniforge3/envs/magenta/lib/python3.8/site-packages/magenta/common/__init__.py", line 20, in <module>
    from .nade import Nade
  File "/Users/theotenaguillo/miniforge3/envs/magenta/lib/python3.8/site-packages/magenta/common/nade.py", line 23, in <module>
    import tensorflow.compat.v1 as tf
  File "/Users/theotenaguillo/miniforge3/envs/magenta/lib/python3.8/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/theotenaguillo/miniforge3/envs/magenta/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/Users/theotenaguillo/miniforge3/envs/magenta/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 36, in <module>
    from tensorflow.python.eager import execute
  File "/Users/theotenaguillo/miniforge3/envs/magenta/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 21, in <module>
    from tensorflow.python.framework import dtypes
  File "/Users/theotenaguillo/miniforge3/envs/magenta/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py", line 32, in <module>
    from tensorflow.python.types import trace
  File "/Users/theotenaguillo/miniforge3/envs/magenta/lib/python3.8/site-packages/tensorflow/python/types/trace.py", line 31, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```
